### ISSUE TITLE
[chore] Add Brikev's commitlint and husky configuration

### ISSUE THREAD

**Issue by kevinccbsg** [BRIKEV/openapi-validator-utils#2]
We still don't have most of the configuration we use in our other libraries. I think we could add CommitLint as we do for [express-jsdoc-swagger](https://github.com/BRIKEV/express-jsdoc-swagger).

- [Dependencies](https://github.com/BRIKEV/express-jsdoc-swagger/blob/master/package.json#L15)
- [Configuration](https://github.com/BRIKEV/express-jsdoc-swagger/blob/master/commitlint.config.js)

We should also connect this linter with a [husky](https://www.npmjs.com/package/husky) pre-push command.

**Comment by khafrewatkins** [comment]
I can work on this for you.

**Comment by kevinccbsg** [comment]
Hi @khafrewatkins, you could create a PR and we will be glad to review it and ✅ it 😃
